pipeline {
  agent { label 'nprod-small' }

    environment {
        hostName = 'happy-friday.c141.drcloud.zone'
        userName = 'ubuntu'
        cloudHome = '/home/ubuntu/'
        browserType = 'chrome:headless'
        shellScriptPath = "/home/ubuntu/DRWPAutoTest/TestcafeInDocker/"
        deployScriptName = 'deploy.sh'
        runTestScriptName = 'runtest.sh'
        cleanScripName = 'clean.sh'
        reportRemote = "${shellScriptPath}report_*.xml"
        reportLocal = 'TestCafeTestResult.xml'
    }

    stages {
        stage('Deploy') {
            steps {
                script {
                    env.sshCmd = "ssh -o StrictHostKeyChecking=no ${env.userName}@${env.hostName}"
                }
                sshagent(credentials:['happy-friday-cicd-cred']) {
                    sh "${env.sshCmd} '(${shellScriptPath}${deployScriptName})'"
                }
            }
        }

        stage('Test') {
            steps {
                sshagent(credentials:['happy-friday-cicd-cred']) {
                    script {
                        env.sshCmd = "ssh -o StrictHostKeyChecking=no ${env.userName}@${env.hostName}"
                    }
                    sh "${env.sshCmd} '(${shellScriptPath}${runTestScriptName} dev)'"
                }
            }
        }
    }
    post {
        always {
            sshagent(credentials:['happy-friday-cicd-cred']) {
                script {
                    env.sshCmd = "ssh -o StrictHostKeyChecking=no ${env.userName}@${env.hostName}"
                    env.sshCpy = "scp -o StrictHostKeyChecking=no ${env.userName}@${env.hostName}"
                }
                sh "${env.sshCmd} '(${shellScriptPath}${cleanScripName})'"
                sh "scp -o StrictHostKeyChecking=no ${env.userName}@${env.hostName}:${env.reportRemote} ${env.reportLocal}"
                junit "${env.reportLocal}"
                sh "rm ${env.reportLocal}"
                sh "${env.sshCmd} '(rm ${env.reportRemote})'"
                emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                to: 'twang@digitalriver.com; ewu@digitalriver.com; jewang@digitalriver.com; alliu@digitalriver.com; cyu@digitalriver.com; tchang@digitalriver.com; tcannon@digitalriver.com',
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"
            }
        }
    }
}
